name = "scintilla-chat"
compatibility_date = "2025-07-16"
pages_build_output_dir = "./build"

[[d1_databases]]
binding = "DB"
database_name = "scintilla-chat"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
migrations_dir = "migrations"
